pylama/core.py
We need to copy `ignore` and `select` lists to keep overiding them per file. Otherwise errors ignored per file will be added to global `options` object after each file.
=> Copy options lists

pylama/core.py, tests.py
Allows to set linters for specific files, e.g.:
`[pylama:dummy.py]`
`linters = pep8,pyflakes`
`[pylama:*js]`
`linters = gjslint`
=> allow the setting of linters for specific files

pylama/main.py
This allows checking files that do not end in `.py`, but are Python
files, e.g. through a shebang line.
Additionally or instead the `allow` function could look for a shebang line like `#!/usr/bin/env python`, but would then have to open the file, which is bad when running it against a directory.
I think that passing a single path to a file should automatically check it.
=> Use auto-force if a single file argument is being passed

README.rst
the "Command line options" section on docs is deprecated.
this pull-request update the docs to same output of pylama==6.3.1
=> update Command line options docs on README.rst

pylama/core.py
If a linter returns `None` instead of a iterable (latest isort version, fix pr: https://github.com/timothycrosley/isort/pull/362) an exceptions is raised. This can intermittently cause (depending on the random order of the linters) pylama to not return any errors at all, thus `passing` the project.
=> Return all errors even if a linter returns `None`

setup.py
I am trying to install pylama system-wide on Arch Linux, which has
pyflakes 1.1.0 already, and running pylama fails with:
> pkg_resources.ContextualVersionConflict: (pyflakes 1.1.0
> (/usr/lib/python3.5/site-packages),
> Requirement.parse('pyflakes==1.0.0'), {'pylama'})
> pkg_resources.DistributionNotFound: The 'pyflakes==1.0.0' distribution
> was not found and is required by pylama
This commit fixes it by only using the package name from
requirements.txt, but not the version.
Alternatively I could imagine replacing the '==' with '>=' to ensure the
minimum requirements are met, which is probably better?!
On the other hand this might not be useful altogether, and instead tools
like pipsi or virtualenvs should be used for pylama only?!
=> [WIP] setup.py: install_requires: remove versions

pylama/lint/pylama_pyflakes.py
Pyflakes reports for every variable if star imports are used.
https://github.com/pyflakes/pyflakes/commit/0532189b34086740d7fe553bd87c0a6cf682a93b
https://github.com/pyflakes/pyflakes/blob/aec68a7847d8dbd1371242f42f9302103a68178f/pyflakes/messages.py#L68-L73
=> Mark all star import related messages with W0401.

pylama/config.py, pylama/main.py
This is meant to provide all information that is available.
It does not include "number", which currently is just the first word
from "msg" itself.
TODO:
What do you think about splitting this, and to have number and message separate?
This would be especially useful when allowing custom output formats.
Ref: https://github.com/klen/pylama/issues/73
=> TBD: Add new "parsable" output format

pylama/core.py, pylama/lint/pylama_mccabe.py
Do not special-case mccabe - it is also not handled in pyflakes.
This uses 'pylama' as the linter name in this case, and also adds an
error number to it for consistency.
Fixes https://github.com/klen/pylama/issues/72.
TODO:
=> Fix SyntaxError handling

pylama/config.py
Ref: https://github.com/klen/pylama/issues/72
=> Make split_csp_str stable to keep the order of provided linters

pylama/errors.py
Currently it would also use "Invalid" as the number, which might come
from a SyntaxError (this is fixed in https://github.com/klen/pylama/pull/75).
=> Error: only use expected numbers

pylama/lint/pylama_pydocstyle.py
This makes it more consistent with other linters.
=> pydocstyle: remove colon after code at start of message

pylama/core.py
It only exists for backwards compatibility and was deprecated in python 3.4.
https://docs.python.org/3/library/functions.html#open
=> Do not use 'U' mode with python 3

pylama/config.py
After using get_default_config_file() since
caaf7952c36213601d6d3cddd370c533cf6b4e32, options.options could be
None as get_default_config_file() will return nothing if no default
config files are being found.
Hence we need to do None checking in setup_logger()
=> Fix pylama crash if default config not exists

pylama/config.py, pylama/lint/pylama_pydocstyle.py
This will pass parameters to pydocstyle, retrieve ignore_decorators if it exists, and then use it.
There was also a bug with ini_path always having been stringified in my testing, so that is also checked now.
=> Allow ignore_decorators to pass to pydocstyle.

pylama/pytest.py
Using `pylama` as `pytest` plugin will fail if `--strict` command line option is used.
According to `pytest` changelog for version 2.2:
> introduce registration for “pytest.mark.*” helpers via ini-files or through plugin hooks. Also introduce a “–strict” option which will treat unregistered markers as errors allowing to avoid typos and maintain a well described set of markers for your test suite. See examples at http://pytest.org/latest/mark.html and its links.
This PR register `pycodestyle` mark used by `pylama` to follow `pytest` strict mode.
=> Prevent fail when used with pytest and --stric argument.

README.rst
* Added the subset of the CLI options when running pylama from python. CLI options like report, abspath and format cannot be used. Also, some of the usable options work as lists while others work as comma separated strings.
* Added the rootdir parameter to check_path() call. Without this parameter, the python code is unable to get the relative paths of files to be audited and results in the following error.
`"[Errno 2] No such file or directory: '<filepath>.py' [undefined]"`
=> Update README.rst for instructions on running from python

.travis.yml, pylama/lint/pylama_pycodestyle.py, test_pylama.py
This correctly parses options of the form "E302,W405", which before this was split into individual characters. This resulted in all errors and/or being considered when ignoring/selecting.
Since specifying just "E" disables all errors, having a list of characters meant that it always encountered an individual "E" and thus disabled all errors.
=> Fix parsing of multi-options for pycodestyle

.travis.yml, tox.ini
This allows for passing flags to pytest, for example to make it quieter:
`tox -- --no-print-logs --capture=fd`
=> Add posargs for tweaking pytest

pylama/config.py
This allows running each tool separately _and_ all using pylama.
Currently you need to duplicate the configs, which makes it much more
painful then it needs to be.
Fixes #69
=> Respect tools own config without pylama: prefix

pylama/core.py
https://github.com/klen/pylama/blob/develop/pylama/core.py#L63
```py
ignore = params.get('ignore', set())
```
In the above line, using `params` reference as it is, so if reaching L65, params will be overwritten, and previous linter specific settings will affect  in the next linter iterations.
```py
ignore |= set(lparams['ignore'].split(','))
```
This issue can be avoided by defensive copy.
L67 `select` has the same issue.
=> Avoid reference usage for linter specific ignore/select

.gitignore, README.rst, dummy.py, pylama/lint/extensions.py, pylama/lint/pylama_mypy.py, requirements-test.txt, tests/test_config.py, tests/test_linters.py
Add MyPy as an available linter.
Closes #40
=> Adds mypy linter

requirements.txt
Added eradicate to the requirements.txt file.
This will prevent the ``WARNING:root:Linter eradicate not found`` error.
=> Added eradicate as a requirement

README.rst
pylama_pylint is deprecated and doesn't need to be installed any more, so this mention in the README/docs is confusing.
=> README: remove mention of installing pylama_pylint

pylama/context.py, tests/test_context.py
For `ignore` and `select` linter params `RunContext.get_params`
transforms parameter value which is comma separated string to set of
values by splitting that string. Subsequent calls to `get_params` (in
case of cache miss or if another instance of `RunContext` is used) tries
to perform this transformation again and fails because `set` doesn't
have split method.
This commit adds additional check before converting CSV string into a
set -- if the value is already a set, we skip this transformation.
=> Fix `RunContext.get_params` for `ignore` and `select` linter params

pylama/context.py, tests/test_context.py
If Context Manager's method `__exit__` returns a true value exception
thrown in `with` block is not propagated. Currently
`RunContext.__exit__` return `self` which is always a true value because
it can never be `None`.
This change fixes `__exit__` method to return `True` only if exception
is expected (i.e. handled by pushing error message into the context). In
other cases exception will always be propagated.
=> `RunContext` swallows unexpected exceptions silently

pylama/context.py, tests/test_context.py
Currently the `RunContext` constructor assigns attributes of the passed in `argparse.Namespace` to itself directly. As a result, when `RunContext.update_params` makes changes, those also persist in the `argparse.Namespace`. In particular this was seen breaking modeline support in #209 where an `ignore` is added via modeline for one file and then persists in all subsequent files.
This changes the `RunContext` constructor to update the object-local containers instead of assigning directly.
=> Fix `RunContext` modifies passed in options object

README.rst
Fixed a typo in Configuration filenames
=> fix typo in README.rst

pylama/lint/pylama_pyflakes.py
Fix #224
`RedefinedInListComp` and `ReturnWithArgsInsideGenerator` were removed at `pyflakes 2.5.0`:
https://github.com/PyCQA/pyflakes/commit/2246217295dc8cb30ef4a7b9d8dc449ce32e603a
=> Fix to adapt to messages removed at pyflakes 2.5.0

README.rst, pylama/config.py, pylama/config_toml.py, pylama/core.py, requirements/requirements-tests.txt, setup.cfg, setup.py, tests/test_config_toml.py
Adds support for TOML configuration files, in particular pyproject.toml inside a `[tool.pylama]` section.
This seemed like the least intrusive way to add support. Reuses the existing vendored inirama with a simple shim to parse TOML tables. The resulting objectis still just a `inirama.Namespace` so no usage changes are needed. All behind a `toml` extras for anyone who doesn't want to pull in the added dependency.
Needed a couple pylint config changes for tests to pass on current pylint version 2.14.4:
* Disable W0012/unknown-option value
* Disable C3001/unnecessary-lambda-assignment in core.py
=> Add optional TOML configuration support

pylama/context.py
I have added a simple check for the issue #214, that skips the regex check SKIP_PATTERN when there are no lines to analyze.
I think that the fact that there is an empty file in the directory should be flagged as en error, but i would like to hear your opinion first before working on it. 
Thanks for your work :)
=> Fix crash in case of empty file in directory
